server:
  port: 8001

spring:
  application:
    name: healthtrack-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/healthtrack?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  
  security:
    user:
      name: admin
      password: admin

logging:
  level:
    com.healthtrack: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# JWT Configuration
jwt:
  secret: mySuperSecureKey_ThisKeyMustBeAtLeast64BytesLong_UseItForHS512Algorithm!!!
  expiration: 86400000 # 24 hours in milliseconds
